---
name: "NFS Disk Share Testing"
version: "0.0.1"
slug: "nfs_disk_share_testing"
description: "Mount disks and share them via NFS"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: system
boot: auto
init: false
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - SYS_MODULE
host_network: true
devices:
  - /dev/sd
full_access: false
options:
  mounts:
    - name: "media_share"
      enabled: false
      label: "frigate"
      point: "/mnt/media-share"
      fstype: "ext4"
      nfs_options:
        - "192.168.1.100(rw,sync,no_subtree_check)"
        - "192.168.1.101(ro,sync,no_subtree_check)"
        - "192.168.2.0/24(ro,sync,no_subtree_check)"

schema:
  mounts:
    - name: str
      enabled: bool
      label: str?
      uuid: str?
      dev: str?
      point: str
      fstype: str
      readonly: bool?
      nfs_options:
        - str
