---
version: 0.0.1
slug: clickhouse_hass_testing
name: Clickhouse_testing
description: >-
  ClickHouse is a high-performance column-oriented DBMS.
  It can be integrated with Home Assistant for storing, processing and quickly analyzing data.
  Use ClickHouse as a reliable storage of historical data on sensors, events and automations.
  This allows you to effectively analyze large volumes of information and create custom dashboards with instant analytics.
url: https://github.com/pessom/hass-addons/tree/main/clickhouse_hass_testing
arch:
  - amd64
init: false
map:
  - ssl
  - share
options:
  logger:
    level: information
schema:
  logger:
    level: list(none|fatal|critical|error|warning|notice|information|debug|trace|test)?

ports:
  8124/tcp: 8124
  9000/tcp: 9000
  9004/tcp: 9004
  9005/tcp: 9005
ports_description:
  8124/tcp: "http port"
  9000/tcp: "tcp port"
  9004/tcp: "mysq_port port"
  9005/tcp: "postgresql_port port"
