---
version: 0.0.0-1
slug: clickhouse_hass_testing
name: clickhouse_testing
description: clickhouse-server
url: https://github.com/pessom/hass-addons/tree/main/clickhouse_hass_testing
arch:
  - amd64
init: false
map:
  - ssl
  - share
ports:
  9000/tcp: 9000
  8123/tcp: 8123
  9009/tcp: 9009
